### ISSUE TITLE
Documentation at https://toytree.readthedocs.io/ is broken

### ISSUE THREAD

**Issue by cndewey** [eaton-lab/toytree#22]
Thanks for this great package; I'm currently using it for a course I'm teaching.  Unfortunately, the documentation at toytree.readthedocs.io appears to have broken after the latest commits.  Any chance this could be fixed quickly so that my students can access the documentation?

Thanks,
Colin

**Comment by eaton-lab** [comment]
Uh oh, sorry about that! I was in the process of refactoring the way the docs was built over the last few days and it went down for a bit. I'm also in the middle of a major-ish update (just pushed 0.1.16), so unless you update the new docs might have some conflicts. Things should be stabilizing now so that this type of thing won't happen again. I hope it's not too hard to catch up on the new version. Glad to hear you're using toytree in your course!
