### ISSUE TITLE
unrecognized arguments skipped: ['layout'] 

### ISSUE THREAD

**Issue by Markkunitomi** [eaton-lab/toytree#29]
I can't seem to use [layout] as an argument when drawing a tree. Was this removed in 0.2.0?
<img width="1025" alt="Screen Shot 2020-02-14 at 4 55 48 PM" src="https://user-images.githubusercontent.com/13501729/74578697-0b5ce400-4f4b-11ea-8440-e40048e981b1.png">

**Comment by eaton-lab** [comment]
Hi @Markkunitomi , the most recent version of toytree is 1.1.2. I recommend updating so that your code will be in sync with the documentation. The `layout` argument was introduced in a later version (I think around v1.0) to replace the older argument `orient`. The layout argument can direct trees to be left, right, up, down, circular, or unrooted. Though the circular and unrooted layouts are still under development.
