### ISSUE TITLE
treenode.add_sister should set sister.up imho

### ISSUE THREAD

**Issue by isaacovercast** [eaton-lab/toytree#32]
So I have a question. Treenode.add_sister is here: 

![image](https://user-images.githubusercontent.com/5974975/81744793-f50be900-94a3-11ea-82ad-154d518a5104.png)

I have a strong prior on what should happen if you pass in a sister treenode to this function. My expectation would be that if I add a new treenode (lets call it 'new') to an already existing treenode object (lets call it 'sis) that new would inherit sis.up. As it is you can get into weird situations (which I have spent quite a bit of time trying to figure out), where you can have weird inconsistencies. For example, if I create a new subtree like this:

new = toytree.tree(newick="({}:0,{}:0):{};".format(sname, anc_name, branch_length))

And then add this tree as sister to a tip on a current tree, the call to add_sister works fine, and the topology is fine if you draw() it, but, new.up is now a reference to a nonsensical node name (in this case '2'). So now when I do `get_mrca_idx_from_tip_labels()` and include either tip in 'new' it tells me '2', which makes no sense.

I'm trying to think of a case where you have sister nodes on a tree where they do not share `.up` values, but I'm not coming up with anything. Can we force `add_sister()` to set `.up` so the new node is consistent?

**Comment by eaton-lab** [comment]
I've been messing with this to try to understand the problem. I'm not sure that I understand... or its possible that it has since been fixed.

Anyways, I added a new feature to `add_sister()` that allows splitting the edge where it is being added so that it creates a newnode, by using the new `split=True` argument. This is a convenience that could be useful to help avoid extra TreeNode or add_child calls. The default setting is split=False, so the default functionality remains the same. 

A notebook example is here: https://github.com/eaton-lab/toytree/blob/master/sandbox/32-add_sister_treenodes.ipynb

Hope this helps,
D
