### ISSUE TITLE
Drawing is very slow when layout='c'

### ISSUE THREAD

**Issue by aleferna12** [eaton-lab/toytree#63]
Hello! I have a relatively big (>8000 sequences) tree, which I would like to draw as a radial tree.

When layout='r', everything works fine, and the tree is drawn in a few seconds. However, when I set layout to 'c' (or 'circular'), the computation seemingly takes forever. After a few hours however I got back my SVG file.

Is there a reason for such a big difference in the time required for running both algorithms? Is there anything I can do to minimize the issue?

Thanks a lot.

**Comment by eaton-lab** [comment]
Hi @aleferna12 , 

Sorry for my late reply. The time to generate layouts will significantly improve in the next update (v. 3.0). The circular layout was created in a fairly simple way at first, and has since been further optimized. 

I will leave this open so I remember to send a message when the update is tested and released.

**Comment by aleferna12** [comment]
Alright! Thank you!
